[package]
name = "wasi_example_main"
version = "0.1.0"
authors = ["ubuntu"]
edition = "2018"

[[bin]]
name = "wasi_example_main"
path = "src/main.rs"

[dependencies]
rand = "0.7.3"
wasm-bindgen = "=0.2.61"
